/**
 * Migration 023 — Explicit barcode source flag (auto-generated vs manual)
 *
 * ── The bug ──────────────────────────────────────────────────────────────
 * Migration 021 made auto-generated barcodes globally unique by adding
 * `products_autobarcode_global_unique`, a partial unique index scoped to
 * `WHERE barcode ~ '^20\d{11}$'` — i.e. it *guesses* a row is
 * auto-generated by pattern-matching the stored barcode value itself
 * (GS1 restricted-range prefix "20" + 13 digits, the exact shape
 * `buildAutoBarcode()` produces).
 *
 * That guess breaks the manual-entry rule as soon as a real-world
 * scenario touches the same numeric shape:
 *   - GS1's 200–299 prefix range is explicitly reserved for
 *     *internal/restricted-circulation use* — exactly the kind of code a
 *     shop or manufacturer hands out for their own private-label
 *     products. A manually typed or scanned 13-digit barcode starting
 *     with "20" is a completely plausible real barcode.
 *   - If Company B manually enters such a code and it happens to already
 *     be in use — by ANY company, auto-generated or not — the global
 *     partial index blocks the INSERT/UPDATE outright. But the spec is
 *     explicit: a manually entered barcode must only be checked against
 *     the CURRENT account; another account already using it (for any
 *     reason) must never block it.
 *
 * In short: whether a row is "auto-generated" was being inferred from
 * the value, not tracked as a fact — exactly what leads to false
 * positives/negatives in validation.
 *
 * ── The fix ──────────────────────────────────────────────────────────────
 * Track the origin explicitly with a real column, set by the application
 * at the moment it decides which code path is running (see
 * routes/products.js) — never derived from the barcode's digits.
 * The global-uniqueness guarantee for auto-generated codes is re-scoped
 * to that column instead of a value-shape regex.
 */
exports.up = async (knex) => {
  console.log('\n[Migration 023] Explicit barcode source flag...')

  const hasColumn = await knex.schema.hasColumn('products', 'barcode_auto_generated')
  if (!hasColumn) {
    await knex.schema.alterTable('products', (t) => {
      t.boolean('barcode_auto_generated').notNullable().defaultTo(false)
    })
    console.log('  + added products.barcode_auto_generated')
  } else {
    console.log('  = products.barcode_auto_generated already exists, skipping')
  }

  // One-time, best-effort backfill for EXISTING rows only: we have no
  // record of how they were originally entered, so the old pattern is the
  // best available signal for historical data. Every row created from
  // this migration forward gets the flag set explicitly by the
  // application instead — this backfill never runs again.
  const AUTO_PATTERN = `^20\\d{11}$`
  const backfilled = await knex.raw(`
    UPDATE products
    SET barcode_auto_generated = true
    WHERE barcode ~ ? AND barcode_auto_generated = false
  `, [AUTO_PATTERN])
  console.log(`  + backfilled ${backfilled.rowCount || 0} legacy auto-pattern row(s)`)

  // Drop the old value-shape-inferred global unique index.
  await knex.raw(`DROP INDEX IF EXISTS products_autobarcode_global_unique`)
  console.log('  - dropped products_autobarcode_global_unique (regex-based)')

  // Replace it with one scoped to the explicit flag — global uniqueness
  // now applies to "rows the application marked as auto-generated",
  // never to "rows whose value happens to look auto-generated".
  const hasIndex = await knex.raw(`
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'products' AND indexname = 'products_autogenerated_barcode_unique'
  `)
  if (hasIndex.rows.length === 0) {
    await knex.raw(`
      CREATE UNIQUE INDEX products_autogenerated_barcode_unique
      ON products (barcode)
      WHERE barcode_auto_generated = true
    `)
    console.log('  + added products_autogenerated_barcode_unique (flag-based)')
  } else {
    console.log('  = products_autogenerated_barcode_unique already exists, skipping')
  }
}

exports.down = async (knex) => {
  await knex.raw(`DROP INDEX IF EXISTS products_autogenerated_barcode_unique`)
  const hasColumn = await knex.schema.hasColumn('products', 'barcode_auto_generated')
  if (hasColumn) {
    await knex.schema.alterTable('products', (t) => {
      t.dropColumn('barcode_auto_generated')
    })
  }
}
