/**
 * scannerRoutes.js
 *
 * Local (same-device) barcode scanner product lookups. No sessions, no
 * cross-device pairing — the scanner runs entirely in the logged-in
 * user's own browser tab and calls these endpoints with their normal
 * auth token.
 *
 * Endpoints (all under /api/v1/scanner):
 *   GET /scanner/products/barcode/:code — barcode lookup (auth required)
 *   GET /scanner/products/fuzzy?q=...   — contains search, barcode-miss fallback (auth required)
 *
 * Mount in server.js:
 *   const scannerRouter = require('./scanner/scannerRoutes')
 *   app.use(`${API}/scanner`, scannerRouter)
 */

const router = require('express').Router()
const db     = require('../db/knex')
const { authenticate } = require('../middleware/index')

async function fetchProductWithStock(productId, companyId) {
  const p = await db('products')
    .where({ id: productId, company_id: companyId, is_active: true })
    .first(
      'id', 'item_code', 'barcode', 'name', 'generic_name', 'company_name',
      'unit', 'sales_rate', 'mrp', 'purchase_rate', 'min_stock', 'is_active',
      db.raw('tax_rate   as vat_percent'),
      db.raw('cc_percent as cc_pct')
    )
  if (!p) return null

  const stockRow = await db('inventory_batches')
    .where({ product_id: productId, company_id: companyId })
    .sum('qty_remaining as total_stock')
    .first()

  const batches = await db('inventory_batches')
    .where({ product_id: productId, company_id: companyId })
    .where('qty_remaining', '>', 0)
    .orderBy('expiry_date', 'asc')
    .select('batch_no', 'expiry_date', db.raw('qty_remaining as qty'))
    .limit(5)

  return { ...p, current_stock: Number(stockRow?.total_stock) || 0, batches }
}

// ══════════════════════════════════════════════════════════════════════════════
// PRODUCT SEARCH ROUTES (used by mobile scanner)
// ══════════════════════════════════════════════════════════════════════════════

/* ── GET /scanner/products/barcode/:code ─────────────────────────────────────
 * Look up a scanned product. `:code` is whatever the camera/scanner decoded,
 * which is now one of two shapes:
 *
 *   1. NEW structured QR payload (JSON string) — generated by the current
 *      QR Code Print page:
 *        { v: 1, accountId: <company_id>, productId: <uuid>, medicineCode }
 *      This is what actually fixes the cross-account collision: it carries
 *      *which account* the QR was generated for and the product's own
 *      globally-unique row id, instead of only the account-specific
 *      medicine code that two different accounts can both use for two
 *      completely different products.
 *
 *   2. LEGACY plain string — a real barcode value, an internal item_code,
 *      or an old-format QR that only ever encoded the medicine code. Every
 *      QR/barcode printed before this fix decodes to one of these, so they
 *      must keep working exactly as before, scoped to the current account.
 *
 * Auth required (JWT forwarded from session) — `req.companyId` comes from
 * the verified JWT, never from the request body/params, so it can't be
 * spoofed by whatever payload the scanned code happens to contain.
 * ─────────────────────────────────────────────────────────────────────────── */
router.get('/products/barcode/:code', authenticate, async (req, res, next) => {
  try {
    const raw = req.params.code?.trim()
    if (!raw) return res.status(400).json({ success: false, message: 'Barcode required' })

    const cols = ['id', 'item_code', 'barcode', 'name', 'generic_name', 'company_name', 'unit',
             'sales_rate', 'mrp', 'purchase_rate', 'min_stock', 'is_active',
             db.raw('tax_rate as vat_percent'), db.raw('cc_percent as cc_pct')]

    // ── Try the structured QR payload first ────────────────────────────
    // A bare barcode/item_code never starts with "{", so this can't
    // misfire against legacy values — falls straight through to the
    // legacy lookup below whenever JSON.parse fails.
    let qrPayload = null
    if (raw.startsWith('{')) {
      try {
        const parsed = JSON.parse(raw)
        if (parsed && typeof parsed === 'object' && parsed.accountId != null) qrPayload = parsed
      } catch { /* not a structured payload — fall through to legacy lookup */ }
    }

    if (qrPayload) {
      // Cross-account guard — this is the actual fix. accountId in the
      // payload is whatever account the QR was PRINTED under; req.companyId
      // is whichever account the scanning user is CURRENTLY logged into.
      // If they differ, this QR was generated by a different account and
      // must never be resolved against this account's products — not even
      // as a medicine-code fallback, which is exactly how the old bug
      // mapped Account A's MD-1 onto Account B's unrelated product.
      if (String(qrPayload.accountId) !== String(req.companyId)) {
        return res.status(403).json({
          success: false,
          code: 'QR_ACCOUNT_MISMATCH',
          message: 'This QR Code belongs to another account and cannot be used in the current account.',
        })
      }

      // Account confirmed — Product ID is the preferred, unique lookup.
      let product = null
      if (qrPayload.productId) {
        product = await db('products')
          .where({ company_id: req.companyId, id: qrPayload.productId, is_active: true })
          .first(...cols)
      }

      // Product ID missing (older structured payload) or that exact row
      // is gone (e.g. deleted since printing) — fall back to medicine
      // code, but still scoped to this same, already-verified account.
      // This never reaches across accounts: qrPayload.accountId already
      // matched req.companyId above, so this WHERE is on the same tenant
      // that owns the code being matched.
      if (!product && qrPayload.medicineCode) {
        product = await db('products')
          .where({ company_id: req.companyId, is_active: true })
          .where(b => b.where({ barcode: qrPayload.medicineCode })
                       .orWhere({ item_code: qrPayload.medicineCode }))
          .first(...cols)
      }

      if (!product) {
        return res.status(404).json({ success: false, message: 'No product found for this QR code' })
      }

      const full = await fetchProductWithStock(product.id, req.companyId)
      return res.json({ success: true, data: full })
    }

    // ── Legacy path — plain barcode / item_code / old-format QR ────────
    // Unchanged from before: always scoped to req.companyId, so two
    // accounts sharing the same medicine code still can't cross-resolve
    // each other's products this way either.
    const code = raw

    // 1. Real barcode column — exact match
    let product = await db('products')
      .where({ company_id: req.companyId, barcode: code, is_active: true })
      .first(...cols)

    // 2. item_code — exact match (internal SKU, also scannable)
    if (!product) {
      product = await db('products')
        .where({ company_id: req.companyId, item_code: code, is_active: true })
        .first(...cols)
    }

    // 3. Case-insensitive fallback on either column
    if (!product) {
      product = await db('products')
        .where({ company_id: req.companyId, is_active: true })
        .where(b => b.whereRaw('LOWER(barcode) = LOWER(?)', [code])
                     .orWhereRaw('LOWER(item_code) = LOWER(?)', [code]))
        .first(...cols)
    }

    if (!product) {
      return res.status(404).json({ success: false, message: 'No product found for this barcode' })
    }

    const full = await fetchProductWithStock(product.id, req.companyId)
    res.json({ success: true, data: full })
  } catch (err) { next(err) }
})

/* ── GET /scanner/products/fuzzy?q=paracetamol&limit=10 ─────────────────────
 * Substring / contains search — barcode-miss fallback (searches name + generic_name).
 * Auth required (JWT forwarded from session).
 * ─────────────────────────────────────────────────────────────────────────── */
router.get('/products/fuzzy', authenticate, async (req, res, next) => {
  try {
    const raw   = (req.query.q || '').toString().trim()
    const limit = Math.min(parseInt(req.query.limit) || 15, 30)

    if (!raw || raw.length < 2) return res.json({ success: true, data: [] })

    const pattern = `%${raw.replace(/[%_]/g, c => '\\' + c)}%`

    const rows = await db('products')
      .where({ company_id: req.companyId, is_active: true })
      .where(b =>
        b.whereRaw('name         ILIKE ?', [pattern])
         .orWhereRaw('generic_name ILIKE ?', [pattern])
         .orWhereRaw('item_code    ILIKE ?', [pattern])
         .orWhereRaw('barcode      ILIKE ?', [pattern])
      )
      .orderByRaw(`
        CASE
          WHEN LOWER(name) LIKE LOWER(?) THEN 0
          WHEN LOWER(generic_name) LIKE LOWER(?) THEN 1
          ELSE 2
        END, name ASC
      `, [`${raw}%`, `${raw}%`])
      .limit(limit)
      .select('id', 'item_code', 'barcode', 'name', 'generic_name', 'company_name', 'unit',
              'sales_rate', 'mrp', 'purchase_rate', 'min_stock', 'is_active',
              db.raw('tax_rate as vat_percent'), db.raw('cc_percent as cc_pct'))

    res.json({ success: true, data: rows })
  } catch (err) { next(err) }
})

module.exports = router
